<a href="https://colab.research.google.com/github/Hangowoon/Newjak_ex/blob/main/py3_nex06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pylab as plt

▶ (실습)Q1. 벡터, 행렬 연산(+, -, *, /, dot)

Q1.1 벡터

v1 = [1,2,3,4,5]

v2 = [6,7,8,9,10]





In [2]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

#벡터 연산  
print ("v1+v2 = ", (v1 + v2) ) #더하기 elementwise sum
print ("v1-v2 = ", (v1 - v2) ) #빼기 elementwise difference
print ("v1*v2 = ", (v1 * v2) ) #곱하기 elementwise product
print ("v1/v2 = ", (v1 / v2) ) #나누기 elementwise division
print ("v1.dot(v2) = ", v1.dot(v2) ) #내적
print ("np.dot (v1,v2) = ", np.dot(v1,v2) )

v1+v2 =  [ 7  9 11 13 15]
v1-v2 =  [-5 -5 -5 -5 -5]
v1*v2 =  [ 6 14 24 36 50]
v1/v2 =  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
v1.dot(v2) =  130
np.dot (v1,v2) =  130


Q1.2 행렬(only dot)

m1 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]    # shape: (?, ?)

m2 = [[1,2], [3,4], [5,6], [7,8]]  # shape: (?, ?)

In [3]:
#행렬 연산
m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #(3,4)
m2 = np.array([[1,2],[3,4],[5,6],[7,8]]) #(4,2)

#shape 
print("m1의 shape : ", m1.shape)
print("m2의 shape : ", m2.shape)



m1의 shape :  (3, 4)
m2의 shape :  (4, 2)


In [4]:
#벡터
v1 = np.array([1,2,3,4,5]) #(5,)
v2 = np.array([6,7,8,9,10]) #(5,)
#행렬
m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #(3,4)
m2 = np.array([[1,2],[3,4],[5,6],[7,8]]) #(4,2)

#벡터-벡터 연산
print (v1+v2)  # [1+6, 2+7, 3+8, 4+9, 5+10] = [7,9,11,13,15]
print (v1-v2)  # [1-6, 2-7, 3-8, 4-9, 5-10] = [-5,-5,-5,-5,-5]
print (v1*v2)  # [1*6, 2*7, 3*8, 4*9, 5*10] = [6,14,24,36,50]
print (v1/v2)  # [1/6, 2/7, 3/8, 4/9, 5/10] = [0.16666, 0.28571, 0.375, 0.44444, 0.5]
print (np.dot(v1,v2)) # [1*6 + 2*7 + 3*8 + 4*9 + 5*10] = 130
#벡터-행렬 연산


#행렬-행렬 연산
print (np.dot(m1,m2))  # (3,2) # [(1*1 + 2*3 + 3*5 + 4*7) (1*2 + 2*4 + 3*6 + 4*8) / 
                               #  (5*1 + 6*3 + 7*5 + 8*7) (5*2 + 6*4 + 7*6 + 8*8) /
                               #  (9*1 +10*3 +11*5 +12*7) (9*2 +10*4 +11*6 +12*8) ] 
                               

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
130
[[ 50  60]
 [114 140]
 [178 220]]


▶ (실습)Q2. 행렬에서 특정 행과 열 성분으로 새로운 행렬 만들기
  - m1 의 0,1행과 1,2,3열로 새로운 행렬 m3 만들기

In [5]:
m3 = np.array([[1,2,3],[5,6,7]])
print ("값 : \n"  ,m3)

값 : 
 [[1 2 3]
 [5 6 7]]


▶ (실습)Q3. shape=(128,) 인 Gaussian noise 생성하기

- v3 

In [6]:
v3 = np.random.randn(128,)
print(v3)

[-0.41773044  1.47721196 -0.54300742 -0.44032253 -0.63291973 -0.01196774
 -0.14532581 -0.14197276 -0.39689487  1.51766616  0.18302581  0.01983085
 -1.77607211 -1.42346056 -0.58097455 -0.67025089  0.73933142 -0.68446349
 -0.25317333  0.98220267  0.62664075  0.44211197  1.17981676 -0.82202419
 -1.14052615 -0.48649778  1.50016494 -0.18230083  0.49279301  0.70856373
  1.06797861 -0.43188391 -1.48087947 -0.44131186 -1.00901806 -0.69168525
  0.08690905 -0.33015724  0.3468337   0.17407035 -0.28764706  0.13827712
  0.17418651 -0.89551653 -0.20461956 -0.230896   -0.40226353  0.10830375
  0.36102933 -0.15383197 -2.31582315  1.47539672  0.48473202 -1.50948067
  0.23279297  0.09325239  1.11399205  0.66662355 -1.20668902 -0.07012576
 -0.9405914  -0.01554791  0.257774    0.36395521  0.32459749 -1.39564459
 -0.75115618 -0.00983674  2.98009959  0.36992028 -0.78922934 -0.19234348
 -1.16941929  0.26516306  0.71457187 -0.02375273 -0.25026961 -0.80569525
  1.16046235  0.37514464 -0.80344184  0.3065998  -1

▶ Q4. 데이터를 neural network 에 feed 할 때, 보통 필요한 변수 두개와 역할을 쓰시오.

In [7]:
# train_loader
# test_loader