<a href="https://colab.research.google.com/github/Hangowoon/Newjak_ex/blob/main/py3_nex02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2. 벡터, 행렬 연산, 그래프 그리기

###1) 라이브러리(패키지) 로드

In [ ]:
import numpy as np

###2) 프린트

In [ ]:
#함수
def print_val(x):
  print ("Type :", type(x))
  print ("Shape :", x.shape)
  print ("값 : \n", x)
  print (" ")

rank 1 np array

In [ ]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

Type : <class 'numpy.ndarray'>
Shape : (3,)
값 : 
 [1 2 3]
 
Type : <class 'numpy.ndarray'>
Shape : (3,)
값 : 
 [5 2 3]
 


rank 2 np array

In [ ]:
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

Type : <class 'numpy.ndarray'>
Shape : (2, 3)
값 : 
 [[1 2 3]
 [4 5 6]]
 


rank 2 zeros

In [ ]:
a = np.zeros((2,2))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (2, 2)
값 : 
 [[0. 0.]
 [0. 0.]]
 


rank 2 ones

In [ ]:
a = np.ones((3,2))
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (3, 2)
값 : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


rank 2 단위 행렬(identity matrix)

In [ ]:
a = np.eye(3,3)
print_val(a)

Type : <class 'numpy.ndarray'>
Shape : (3, 3)
값 : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
