<a href="https://colab.research.google.com/github/Hangowoon/Newjak_ex/blob/main/py3_nex04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3. 파이토치 기초

In [1]:
import torch

In [5]:
#함수
def print_val(x):
  print ("Type :", type(x))
  print ("Shape :", x.shape)
  print ("값 : \n", x)
  print (" ")

In [6]:
x = torch.rand(2,3,2) #uniform: 0~1 사이 모든 값들이 나올 확률이 같음
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 3, 2])
값 : 
 tensor([[[0.8121, 0.5058],
         [0.3196, 0.4573],
         [0.8172, 0.3289]],

        [[0.4058, 0.6293],
         [0.3097, 0.3331],
         [0.9932, 0.8878]]])
 


In [8]:
x = torch.randn(2,3) #Gaussian : 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 3])
값 : 
 tensor([[ 0.5587,  1.1734,  0.1291],
        [ 0.1407, -0.2800, -0.0177]])
 


In [14]:
x = torch.randperm(20) #0~n-1까지 값을 원소로 갖는 배열 -> 랜덤 배열
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([20])
값 : 
 tensor([ 0,  7,  1, 19,  2, 15, 17, 16, 18, 11,  8, 12,  9,  5,  4,  3, 13,  6,
        10, 14])
 


In [15]:
# [start, end] 구간을 step 단위로 나눠서 배열로 생성
x = torch.arange(0,3,step=0.5)
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([6])
값 : 
 tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [16]:
print_val(torch.ones(3,4))

Type : <class 'torch.Tensor'>
Shape : torch.Size([3, 4])
값 : 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 


In [18]:
print_val(torch.zeros(3,4))

Type : <class 'torch.Tensor'>
Shape : torch.Size([3, 4])
값 : 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [19]:
print_val(torch.Tensor(2,4))

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 4])
값 : 
 tensor([[3.8490e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 6.4460e-44, 1.3733e-14, 6.4069e+02]])
 


In [20]:
print_val(torch.Tensor([2,3]))

Type : <class 'torch.Tensor'>
Shape : torch.Size([2])
값 : 
 tensor([2., 3.])
 


In [21]:
print_val(torch.Tensor([[2,3],[3,4]]))

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 2])
값 : 
 tensor([[2., 3.],
        [3., 4.]])
 


In [22]:
#텐서 타입 변환
x = torch.FloatTensor(2,3)
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 3])
값 : 
 tensor([[1.2229e-34, 0.0000e+00, 7.0976e+22],
        [1.0903e+27, 7.1220e+28, 6.9397e+22]])
 


In [24]:
x = x.type_as(torch.IntTensor())
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 3])
값 : 
 tensor([[          0,           0, -2147483648],
        [-2147483648, -2147483648, -2147483648]], dtype=torch.int32)
 


In [26]:
#텐서 크기 반환
torch.FloatTensor(3,4,5).size()

torch.Size([3, 4, 5])

In [27]:
# numpy array -> torch tensor
import numpy as np
np_x = np.ndarray((2,3), dtype = int)
print_val(np_x)

Type : <class 'numpy.ndarray'>
Shape : (2, 3)
값 : 
 [[119716560         0         0]
 [        0         0         0]]
 


In [28]:
x = torch.from_numpy(np_x)
print_val(x)

Type : <class 'torch.Tensor'>
Shape : torch.Size([2, 3])
값 : 
 tensor([[119716560,         0,         0],
        [        0,         0,         0]])
 


In [29]:
# torch tensor -> numpy array
tp_x = x.numpy()
print_val(tp_x)

Type : <class 'numpy.ndarray'>
Shape : (2, 3)
값 : 
 [[119716560         0         0]
 [        0         0         0]]
 
